# Generated by Django 4.0.4 on 2022-04-28 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('haberler', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='makale',
            old_name='yayinlanma_tarihi',
            new_name='yayinlama_tarihi',
        ),
    ]
